version: '3.8'

services:
  mapper-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development
      - DEBUG=True
      - DATABASE_URL=sqlite:///./data/mapper.db
      - GEOCODING_SERVICE=open-meteo
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: PostgreSQL for production-like testing
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: mapper
      POSTGRES_USER: mapper
      POSTGRES_PASSWORD: mapper_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    profiles:
      - production

volumes:
  postgres_data: